# Generated by Django 4.0.2 on 2022-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questions',
        ),
    ]
