# Generated by Django 4.0.2 on 2022-02-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_question_answer_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='fromUser',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='toUser',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='surveygroup',
            name='questions',
        ),
        migrations.AddField(
            model_name='surveygroup',
            name='group_name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='survey_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.surveygroup'),
            preserve_default=False,
        ),
    ]
