# Generated by Django 4.0.2 on 2022-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveygroup_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveygroup',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группа'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestions',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(to='surveys.SurveyGroup'),
        ),
    ]
