# Generated by Django 3.2.9 on 2022-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_surveygroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveygroup',
            name='questions',
            field=models.ManyToManyField(blank=True, to='surveys.SurveyQuestions'),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='survey_group',
            field=models.ManyToManyField(blank=True, to='surveys.SurveyGroup'),
        ),
    ]
