# Generated by Django 4.0.2 on 2022-02-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveyquestions_survey_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveygroup',
            name='questions',
            field=models.ManyToManyField(to='surveys.SurveyQuestions'),
        ),
    ]
